name: zad2:GitHub_Zadanie 2

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    # Definicja systemu do instalacji na weźle roboczym
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.0
          buildkitd-flags: --debug

      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      # Logowanie do Dockerhub-a
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Budowa obrazu dla dwóch architektur sprzętowych
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64 #,linux/386 #nie ma node/alpine na i386
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zadanie2:zadanie
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2:zadanie
          cache-to: type=inline
        #  tags: |
        #    ${{ secrets.DOCKERHUB_USERNAME }}/gha_lab10:zadv1
        #  cache-from: type=registry,ref=gha_lab10:zadv1
        #  cache-to: type=registry,ref=gha_lab10:zadv1,mode=max
        #  tags: |
        #    ${{ secrets.DOCKERHUB_USERNAME }}/gha_lab10:zadv1
        #  cache-from: type=gha
        #  cache-to: type=gha,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
